global using System.Reflection;
global using Chess;
global using Chess.BoardRepresentation;
global using ChessMasterQuiz.Misc;
global using UserRepresentation;
global using static Chess.Colour;
global using static Chess.Notation;
global using static Chess.PieceType;
global using static ChessMasterQuiz.Chess.ChessPieces;
global using static ChessMasterQuiz.Helpers.ControlHelper;
global using static ChessMasterQuiz.Helpers.FormatDirection;
global using static ChessMasterQuiz.Helpers.Helper;
global using static ChessMasterQuiz.Misc.ContextTagType;
global using static ChessMasterQuiz.Misc.PasswordRequirementLevel;
global using static UserRepresentation.UserHelper;
global using DCT = ChessMasterQuiz.Misc.DataContextTag;
